# General settings
autoDedupe: true
blockExoticSubdeps: true
engineStrict: true
minimumReleaseAge: 7200 # 5 days
strictDepBuilds: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 129600 # 90 days
verifyDepsBeforeRun: error

# No workspace
packages:
  - '.'
